[package]
name = "devlish-wasm-compiler"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
devlish-core = { path = "../devlish_core", default-features = false }
serde_json = "=1.0.150"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
