import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = resolve(
  __dirname,
  "../../../crates/devlish_wasm_runner/target/wasm32-unknown-unknown/release/devlish_wasm_runner.wasm"
);

const wasmBytes = readFileSync(wasmPath);
const base64 = wasmBytes.toString("base64");

const outDir = resolve(__dirname, "../src/generated");
mkdirSync(outDir, { recursive: true });

writeFileSync(
  resolve(outDir, "wasm-base64.ts"),
  `// Auto-generated by scripts/inline-wasm.mjs. Do not edit.\nexport const WASM_BASE64 = "${base64}";\n`
);

console.log(
  `Inlined WASM binary: ${wasmBytes.length} bytes -> ${base64.length} chars base64`
);
